version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  
  kafka:
    image: wurstmeister/kafka
    ports: 
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  
  product:
    build: ./product
    depends_on: 
      - "kafka"
      - "zookeeper"
    ports: 
      - "3000:3000"
    network_mode: "host"

  client:
    build: ./client
    depends_on: 
      - "kafka"
      - "zookeeper"
    ports: 
      - "3001:3001"
    network_mode: "host"
  
  order:
    build: ./order
    depends_on: 
      - "kafka"
      - "zookeeper"
    ports: 
      - "3002:3002"
    network_mode: "host"
  
  log:
    build: ./logs
    depends_on: 
      - "kafka"
      - "zookeeper"
    ports: 
      - "3003:3003"
    network_mode: "host"